### PR TITLE
Adding annotations parameter to master, client and data

### PR DESCRIPTION
**Pull request by miro-grapeup**
*Description of changes:*
Adding new annotations parameter to be able to annotate master, client or data pods.

This can be helpful when user needs to set some annotations to pods, eg. to mark them for backup/restore tools.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by DerekHeldtWerle** [comment]
Hey @miro-grapeup thanks for the PR!

Given that the annotations you added are specific to the pods the `statefulsets` spin up, I think something like `podAnnotations` would be a more appropriate variable name to future proof against users potentially wanting to set annotations on the `statefulsets` themselves. Also, if you could add the new fields to the [README](https://github.com/Viasat/opendistro-elastic-community/blob/feat/helm-chart/open-distro-elasticsearch-kubernetes/helm/README.md#configuration) that would be greatly appreciated!

**Comment by miro-grapeup** [comment]
Hey @DerekHeldtWerle!

I agree with the naming and I have already updated the changes (also for README file)

**Comment by DerekHeldtWerle** [comment]
@miro-grapeup tested and everything looks great! Forgot to ask in my previous comment, but would you mind bumping the [version](https://github.com/Viasat/opendistro-elastic-community/blob/feat/helm-chart/open-distro-elasticsearch-kubernetes/helm/opendistro-es/Chart.yaml#L12) to `1.1.0`?

**Comment by miro-grapeup** [comment]
@DerekHeldtWerle  no problem - it is added. Feel free to merge the changes :)

**Comment by DerekHeldtWerle** [comment]
@miro-grapeup Awesome, thanks again!

**Pull request merged**
